### ISSUE TITLE
Error  from gpt2_client import GPT2Client

### ISSUE THREAD

**Issue by Igor-Shabalin** [rish-16/gpt2client#14]
**Describe the bug**
I get an import error module 'tensorflow.python.util.compat' has no attribute 'v1'

**To Reproduce**
1. Imported `gpt2_client`

>>> from gpt2_client import GPT2Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/proba/test/lib/python3.6/site-packages/gpt2_client/__init__.py", line 1, in <module>
    from gpt2_client.gpt2_client import GPT2Client
  File "/home/pi/proba/test/lib/python3.6/site-packages/gpt2_client/gpt2_client.py", line 15, in <module>
    import gpt_2_simple as gpt2
  File "/home/pi/proba/test/lib/python3.6/site-packages/gpt_2_simple/__init__.py", line 1, in <module>
    from .gpt_2 import *
  File "/home/pi/proba/test/lib/python3.6/site-packages/gpt_2_simple/gpt_2.py", line 23, in <module>
    from gpt_2_simple.src import model, sample, encoder, memory_saving_gradients
  File "/home/pi/proba/test/lib/python3.6/site-packages/gpt_2_simple/src/memory_saving_gradients.py", line 13, in <module>
    setattr(tf.compat.v1.GraphKeys, "VARIABLES", "variables")
AttributeError: module 'tensorflow.python.util.compat' has no attribute 'v1'

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
I use Tensorflow 1.5 because other versions do not work with my processors Intel Xeon  X5675

**Comment by rish-16** [comment]
Hello there,

Let me look into it asap. Usually, with other OSs and TF versions, the installation isn't much of a hassle. Do sit tight; I'll get back to you on this. Thank you for your patience :)

**Comment by Igor-Shabalin** [comment]
Good afternoon. I build version 1.14 for my processor without AVX. Now everything works as it should. Thank you, the problem is no longer relevant.

**Comment by rish-16** [comment]
Cheers!
